/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * N: Name (アクセシブルな名前)
 * M: Media (メディア)
 * C: Code (コード)
 */
export type ID = string;
export type Level = 'MUST' | 'SHOULD' | 'MAY';
export type AutoCheckFeasibility = 'yes' | 'no' | 'mixed';
export type ScNumber =
	| '1.1.1'
	| '1.2.1'
	| '1.2.2'
	| '1.2.3'
	| '1.2.4'
	| '1.2.5'
	| '1.2.6'
	| '1.2.7'
	| '1.2.8'
	| '1.2.9'
	| '1.3.1'
	| '1.3.2'
	| '1.3.3'
	| '1.4.1'
	| '1.4.2'
	| '1.4.3'
	| '1.4.4'
	| '1.4.5'
	| '1.4.6'
	| '1.4.7'
	| '1.4.8'
	| '1.4.9'
	| '2.1.1'
	| '2.1.2'
	| '2.1.3'
	| '2.2.1'
	| '2.2.2'
	| '2.2.3'
	| '2.2.4'
	| '2.2.5'
	| '2.3.1'
	| '2.3.2'
	| '2.4.1'
	| '2.4.2'
	| '2.4.3'
	| '2.4.4'
	| '2.4.5'
	| '2.4.6'
	| '2.4.7'
	| '2.4.8'
	| '2.4.9'
	| '2.4.10'
	| '3.1.1'
	| '3.1.2'
	| '3.1.3'
	| '3.1.4'
	| '3.1.5'
	| '3.1.6'
	| '3.2.1'
	| '3.2.2'
	| '3.2.3'
	| '3.2.4'
	| '3.2.5'
	| '3.3.1'
	| '3.3.2'
	| '3.3.3'
	| '3.3.4'
	| '3.3.5'
	| '3.3.6'
	| '4.1.1'
	| '4.1.2'
	| '1.3.4'
	| '1.3.5'
	| '1.3.6'
	| '1.4.10'
	| '1.4.11'
	| '1.4.12'
	| '1.4.13'
	| '2.1.4'
	| '2.2.6'
	| '2.3.3'
	| '2.5.1'
	| '2.5.2'
	| '2.5.3'
	| '2.5.4'
	| '2.5.5'
	| '2.5.6'
	| '4.1.3'
	| '2.4.11'
	| '2.4.12'
	| '2.4.13'
	| '2.5.7'
	| '2.5.8'
	| '3.2.6'
	| '3.3.7'
	| '3.3.8'
	| '3.3.9';
export type Phase =
	| '要件定義'
	| 'システム設計'
	| '情報設計'
	| 'UIデザイン'
	| 'フロントエンド実装'
	| 'バックエンド実装';
export type A11YChecklist = A11YCheckItem[];

export interface A11YCheckItem {
	id: ID;
	title: string;
	check: string;
	checkDevOps: string;
	level: Level;
	autocheck: AutoCheckFeasibility;
	sc: ScNumber[];
	dependencies?: ID[];
	phases: Phase[];
	target: ('ページ全体' | '画像' | 'インタラクティブ要素')[];
	reason?: string[];
	spec?: ('html' | 'aria1.2' | 'aria1.3')[];
	reference?: string[];
	exception?: string[];
	keywords?: string[];
}
