name: Test

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22

      - name: Cache dependencies
        id: cache-depends
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: '**/node_modules'
          key: cache-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-depends.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --check-files

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      # - name: Test
      #   run: yarn test
